name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check Formatting
        run: cargo fmt --check
      - name: Clippy Linter
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Tests
        run: cargo test --verbose
      - name: Build Release
        run: cargo build --release --verbose
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: earplugger-x86_64-pc-windows-msvc
          path: target/release/earplugger.exe
